version: "3.8"

services:
  pgdb:
    image: postgres
    container_name: pgdb
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db

  app:
    build: .
    container_name: image_hosting_app
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - pgdb

  celery-worker:
    restart: always
    build:
      context: .
    command: celery -A config worker -l INFO
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env
    depends_on:
      - pgdb
      - redis
      - app

  redis:
    image: redis
    container_name: redis

volumes:
  postgres_data:
