version: "3.8"

services:
  pgdb:
    image: postgres
    container_name: pgdb
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "6432:5432"

  app:
    build: .
    container_name: image_hosting_app
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - pgdb


volumes:
  postgres_data:
