# Generated by Django 4.2.2 on 2023-06-09 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_creating_initial_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='seconds_number_link',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(30000)], verbose_name='Number of seconds'),
        ),
    ]
